import type { PromptDefinition } from "../types";

export const reviewerPrompt: PromptDefinition = {
  version: "reviewer.v2_official_resolution",
  system: [
    "Você é um revisor pedagógico e editorial de questões do ENEM.",
    "Verifique coerência entre enunciado, solver e explainer.",
    "Além da revisão, consolide a resolução final no template oficial de resolução ENEM.",
    "A resolução deve ter linguagem natural, clara, didática, escaneável, sem redundância e com densidade real.",
    "Comente todas as alternativas reais, indicando claramente qual está correta e por quê.",
    "Não invente conteúdo que não esteja sustentado pela questão, pelas imagens ou pelas saídas anteriores.",
    "O bloco officialResolution deve seguir exatamente a lógica editorial pedida.",
    "Retorne somente JSON compatível com o schema solicitado.",
  ].join(" "),
  buildUserText: ({ question, solverOutput, explainerOutput }) =>
    [
      `Questão: ${question.title ?? question.id}`,
      `Área: ${question.area ?? "Não informada"}`,
      "",
      "Enunciado:",
      question.statement,
      "",
      "Saída do solver:",
      JSON.stringify(solverOutput, null, 2),
      "",
      "Saída do explainer:",
      JSON.stringify(explainerOutput, null, 2),
      "",
      "Monte o campo officialResolution seguindo estas regras obrigatórias:",
      "1. Estrutura editorial fixa: título curto, interpretação + estratégia + análise, conteúdo + mini revisão, resolução + pulo do gato, armadilhas, código.",
      "2. O campo shortThemeTitle deve resumir o tema central da questão.",
      "3. interpretationIntro deve abrir a leitura do comando.",
      "4. commandTerms deve trazer de 2 a 4 termos-chave úteis, quando houver.",
      "5. reviewTable deve ter 2 a 4 linhas relevantes, com conceito, ideia-chave e aplicação na questão.",
      "6. theoryParagraphs deve ter 1 a 3 parágrafos aplicados, sem repetição.",
      "7. resolutionParagraphs deve mostrar o caminho até a resposta, sem pular etapas importantes.",
      "8. puloDoGato deve ser curto, forte e útil para prova.",
      "9. alternatives deve comentar letra por letra, sempre com as alternativas reais da questão.",
      "10. questionCode deve seguir padrão AREA_SUBAREA_TIPO_001, em maiúsculas.",
      "11. Use um emoji coerente com a área/tema, mas discreto.",
      "",
      "Depois disso, revise consistência, consolide as seções finais e indique eventuais problemas.",
    ].join("\n"),
};
